### ISSUE TITLE
SyntaxError: Expected double-quoted property name in JSON at position 959

### ISSUE THREAD

**Issue by marcguillemdev** [vendure-ecommerce/ngx-translate-extract#36] opened 2024-01-18 17:30 UTC
The following error is displayed when executing the **i18n:extract** command: 
- An error occurred: SyntaxError: Expected double-quoted property name in JSON at position 959.

I have been checking different files until I found the cause and it is the following class: 

```
import { MatPaginatorIntl } from '@angular/material/paginator';

export class PaginatorIntl implements MatPaginatorIntl {

}
```
If I import the class "MatPaginatorIntl" and implement it as in the example above, the error is displayed. If I remove the import or do not implement it the error disappears. I don't know why this is happening, maybe the JSON compiler is misinterpreting the file or I don't know what could be going on.

To reproduce the error just run the following command on the above class:
`ngx-translate-extract --input ./paginator-intl.ts --output ./src/assets/i18n/error_reproduce.json --clean --format json`

Angular version: 16
ngx-translate version-extract: 8.3.0

**Comment by pmpak** [comment] 2024-01-21 20:07
This might be the same as #24 which was addressed in #30. Since you are using Angular 16, could you try installing v8.2.1 and see if that works?

**Comment by marcguillemdev** [comment] 2024-01-27 16:04
@pmpak thanks for your response. It works with version 8.2.1, but why doesn't it work on the latest version 8.3.0? In the readme it clearly says that we need v8x for Angular 13 to 16, that's why I chose the latest v8.

**Comment by michaelbromley** [comment] 2024-01-30 11:02
Hi @pmpak, I guess there was a regression introduced somewhere between 8.2.1 -> 8.3.0? If 8.2.1 is working for you, I'd advise to just stick with that.

**Closed** 2024-07-10 12:40 UTC
